# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Puzzle.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(337, 292)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 411, 301))
        self.widget.setStyleSheet("background-color: rgb(36, 52, 71);\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(60, 20, 81, 71))
        self.pushButton.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";\n"
"        ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 20, 81, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 20, 81, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 90, 81, 71))
        self.pushButton_4.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 90, 81, 71))
        self.pushButton_5.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 90, 81, 71))
        self.pushButton_6.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 160, 81, 71))
        self.pushButton_7.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 160, 81, 71))
        self.pushButton_8.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 160, 81, 71))
        self.pushButton_9.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 24pt \"RomanD\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.back = QtWidgets.QPushButton(self.widget)
        self.back.setGeometry(QtCore.QRect(40, 240, 31, 31))
        self.back.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font: 24pt \"RomanD\";")
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(self.widget)
        self.next.setGeometry(QtCore.QRect(80, 240, 31, 31))
        self.next.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font: 24pt \"RomanD\";")
        self.next.setObjectName("next")
        self.bfs = QtWidgets.QPushButton(self.widget)
        self.bfs.setGeometry(QtCore.QRect(120, 240, 51, 23))
        self.bfs.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 9pt \"RomanD\";\n"
"")
        self.bfs.setObjectName("bfs")
        self.astarM = QtWidgets.QPushButton(self.widget)
        self.astarM.setGeometry(QtCore.QRect(170, 240, 51, 23))
        self.astarM.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 9pt \"RomanD\";")
        self.astarM.setObjectName("astarM")
        self.dfs = QtWidgets.QPushButton(self.widget)
        self.dfs.setGeometry(QtCore.QRect(220, 240, 51, 23))
        self.dfs.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 9pt \"RomanD\";\n"
"")
        self.dfs.setObjectName("dfs")
        self.astarE = QtWidgets.QPushButton(self.widget)
        self.astarE.setGeometry(QtCore.QRect(270, 240, 51, 23))
        self.astarE.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 9pt \"RomanD\";")
        self.astarE.setObjectName("astarE")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 269, 141, 21))
        self.label.setStyleSheet("background-color: rgb(201, 217, 207);\n"
"font: 9pt \"RomanD\";")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "1"))
        self.pushButton_2.setText(_translate("Dialog", "6"))
        self.pushButton_3.setText(_translate("Dialog", "5"))
        self.pushButton_4.setText(_translate("Dialog", "8"))
        self.pushButton_5.setText(_translate("Dialog", "3"))
        self.pushButton_6.setText(_translate("Dialog", "4"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_8.setText(_translate("Dialog", "2"))
        self.pushButton_9.setText(_translate("Dialog", "1"))
        self.back.setText(_translate("Dialog", "<"))
        self.next.setText(_translate("Dialog", ">"))
        self.bfs.setText(_translate("Dialog", "BFS"))
        self.astarM.setText(_translate("Dialog", "A* M"))
        self.label.setText(_translate("Dialog", " Choose Algorithm"))
        self.dfs.setText(_translate("Dialog", "DFS "))
        self.astarE.setText(_translate("Dialog", "A* E"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
